### ISSUE TITLE
Declaration of Mockery\Adapter\Phpunit\MockeryPHPUnitIntegration::assertPostConditions() must be compatible

### ISSUE THREAD

**Issue by GaryJones** [Yoast/wp-test-utils#26]
Reporting here, but the solution may lay here, PHPUnitPolyfills, or maybe even BrainMonkey.

I'm getting a fatal error for different signatures with particular dependency version combinations. See https://github.com/Parsely/wp-parsely/runs/3718887982?check_suite_focus=true

> PHP Fatal error:  Declaration of Mockery\Adapter\Phpunit\MockeryPHPUnitIntegration::assertPostConditions() must be compatible with Yoast\PHPUnitPolyfills\TestCases\TestCase::assertPostConditions(): void in /home/runner/work/wp-parsely/wp-parsely/vendor/yoast/wp-test-utils/src/BrainMonkey/TestCase.php on line 14

That test has:
- PHP 7.2
- [No PHPUnit or Mockery declared dependencies](https://github.com/Parsely/wp-parsely/blob/feature/improve-test-environment/composer.json#L18-L26) in `composer.json` - just `wp-test-utils` at `^1`.
- The `composer install` via the GitHub Action adds:
  - brain/monkey (2.6.0)
  - mockery/mockery (1.3.5)
  - phpunit/phpunit (8.5.21)

According to https://phpunit.de/supported-versions.html, then PHP 7.2 will try and use PHPUnit 8 (but can use PHPUnit 7).

BrainMonkey 2.6.0 [allows for mockery](https://github.com/Brain-WP/BrainMonkey/blob/7042140000b4b18034c0c0010d86274a00f25442/composer.json#L31) at `>=0.9 <2`.

The [PHP 7.1 test](https://github.com/Parsely/wp-parsely/runs/3718887932?check_suite_focus=true) has combinations (brain/monkey (2.6.0), mockery/mockery (1.3.5), phpunit/phpunit (7.5.20)) which work fine.

The [PHP 7.3 test](https://github.com/Parsely/wp-parsely/runs/3718888050?check_suite_focus=true) also has good combinations (brain/monkey (2.6.0), mockery/mockery (1.4.4), phpunit/phpunit (9.5.10)).

**Comment by jrfnl** [comment]
@GaryJones I've had a quick look, but this is an interesting one. I can already tell you that the problem (AFAICS) is **not** in WP Test Utils nor in PHPUnit Polyfills.

I suspect the problem is, that somewhere in the test setup used, the `PHPUnit_Framework_TestCase` gets declared (most likely as an alias for `\PHPUnit\Framework\TestCase`.

That declaration then causes Mockery to take the wrong path in the below condition and to load the `MockeryPHPUnitIntegrationAssertPostConditionsForV7AndPrevious` trait instead of the `MockeryPHPUnitIntegrationAssertPostConditionsForV8` trait.

https://github.com/mockery/mockery/blob/472fa8ca4e55483d55ee1e73c963718c4393791d/library/Mockery/Adapter/Phpunit/MockeryPHPUnitIntegration.php#L25-L29

Neither WP Test Utils, nor PHPUnit Polyfills create that alias and, as far as I can see, neither does BrainMonkey, so the question remains: where **does** it get declared ?

**Comment by GaryJones** [comment]
After chatting to @jrfnl , it turns out, the wp-parsely code had a **unit** test (a test class that was based on `Yoast\WPTestUtils\BrainMonkey\TestCase`) that was secretly hiding in my directory of **integration** tests (which load WordPress).

By temporarily deleting the unit test file, the PHP 7.2 CI run was able to pass.

The suspicion is that WordPress itself was declaring the `PHPUnit_Framework_TestCase` class alias, and so when the unit test was run, it loaded the wrong Mockery trait as Juliette described.

The solution then, is to separate out the unit tests from the integration tests (separate directory/testsuite/bootstrap as needed), so that WordPress isn't loaded for the unit tests, but is still loaded for the integration test.
